<p><a href="#download_files">Skip introduction</a></p>
<p>Feel free to send email if you have questions. Let us know if you have
any problems or would like assistance getting started.</p> 

<p>General documentation for LaGriT can be found at the URL: <a href='http://lagrit.lanl.gov'>lagrit.lanl.gov</a></p>

<p>Documentation for each LaGriT module can be found at the URL: <a href='http://lagrit.lanl.gov/manual.shtml'>lagrit.lanl.gov/manual.shtml</a></p>

<p>Some examples and project archives can be found in: <a href='http://meshing.lanl.gov/proj'>meshing.lanl.gov/proj</a></p>

<p>If you have any publications, presentations or web pages that illustrate 
the application you are working on, we would appreciate it if you would 
send me citations, URL's or copies of the work.</p>

<p>There are also libraries available but they are only necessary if you 
plan to write your own modules. They are on the FTP site and you are 
welcome to download.</p>

<p>The graphics/code output formats that are normally used are:
<ul>
<li><a href='http://www.paraview.org'>ParaView</a> (free)</li>
<li><a href='https://computing.llnl.gov/vis/visit.shtml'>VISIT</a> (free)</li>
<li><a href='http://laws.lanl.gov/XCM/gmv/GMVHome.html'>GMV</a> (commercial)</li>
<li><a href='http://www.avs.com'>AVS</a> (commercial) </li>
<li><a href='http://www.tecplot.com'>Tecplot</a> (commercial)</li>
<li><a href='http://fehm.lanl.gov'>FEHM</a> (Subsurface Flow and Transport)</li>
<li><a href='http://www.openchannelsoftware.com/projects/GeoFEST'>GEOFEST</a> (Geophysical Finite Element Simulation Tool)</li>
</ul>
</p>

<p>These are not related to LaGriT and may be obtained from their respective sources.</p>

<p>
For demos and examples see: <a href='http://meshing.lanl.gov/proj'>meshing.lanl.gov/proj</a></p>

<p>To run LaGriT just type: <b>lagrit_YOUR_OS_o</b> and enter commands from the command line.<br /> 
For example at the first command prompt you can type: <b>infile demo.lgi</b> <br />
To run in background from a LaGriT control file type:<br />
<b>lagrit_YOUR_OS_o < demo.lgi</b> <br />
LaGriT modules can also be called from within a Fortran/C program. See documentation.</p>

<a id="download_files">
